FROM rabbitmq:3-management

LABEL authors="sunnyk_engineosol"

EXPOSE 5672 15672

# Optional environment variables for username/password
ENV RABBITMQ_DEFAULT_USER=admin
ENV RABBITMQ_DEFAULT_PASS=admin