import csv
import random
from datetime import datetime, timedelta

# List of hotel_ids taken from attached file (truncated for sample)
hotel_ids = [
    "sineb-the-singapore-edition",
    "sinjw-jw-marriott-hotel-singapore-south-beach",
    "sinxr-the-st-regis-singapore",
    "sinwh-w-singapore-sentosa-cove",
    "sincy-courtyard-singapore-novena",
    "sinwi-the-westin-Singapore",
    "ncejw-jw-marriott-cannes",
    "ncemd-le-meridien-nice",
    "pardp-marriotts-village-dile-de-France",
    "parsi-sheraton-paris-charles-de-gaulle-airport-hotel",
    "ncedf-five-seas-cannes-a-member-of-design-hotels",
    "laspe-element-las-vegas-symphony-park",
    "laspa-ac-hotel-las-vegas-symphony-park",
    "lastd-the-english-hotel-las-vegas-a-tribute-portfolio-hotel",
    "lasnv-residence-inn-las-vegas-convention-center",
    "lasfi-fairfield-inn-las-vegas-convention-center",
    "lashh-residence-inn-las-vegas-hughes-center",
    "lasvw-the-westin-las-vegas-hotel-and-spa",
    "lasbl-bellagio-a-luxury-collection-resort-and-casino-las-vegas",
    "lasco-the-cosmopolitan-of-las-vegas-autograph-collection",
    "lasvd-vdara-hotel-and-spa-mgm-collection",
    "lasgm-mgm-grand-hotel-and-casino",
    "laspm-park-mgm-las-vegas-a-tribute-portfolio-resort",
    "lasny-new-york-new-york-hotel-and-casino-mgm-collection",
    "lasex-excalibur-hotel-and-casino-mgm-collection",
    "lastw-towneplace-suites-las-vegas-stadium-district",
    "laslx-luxor-hotel-and-casino-mgm-collection",
    "lasmb-mandalay-bay-resort-and-casino-mgm-collection",
    "lasdl-w-las-vegas",
    "lascy-courtyard-by-marriott-las-vegas-stadium-area",
    "lasfs-fairfield-inn-and-suites-las-vegas-stadium-area",
    "lasri-residence-inn-by-marriott-las-vegas-stadium-area",
    "lasne-towneplace-suites-las-vegas-north-i-15",
    "lasea-element-las-vegas-airport",
    "lasgr-residence-inn-las-vegas-henderson-green-valley",
    "lasgv-courtyard-las-vegas-henderson-green-valley",
    "lassa-springhill-suites-las-vegas-airport",
    "lasta-towneplace-suites-las-vegas-airport-south",
    "lasvr-residence-inn-las-vegas-airport",
    "lasno-fairfield-inn-and-suites-las-vegas-northwest",
    "lasel-element-las-vegas-summerlin",
    "lasha-aloft-henderson",
    "lashd-springhill-suites-las-vegas-henderson",
    "lashn-towneplace-suites-las-vegas-henderson",
    "lasrh-residence-inn-las-vegas-south-henderson",
    "laswi-the-westin-lake-las-vegas-resort-and-spa",
    "nycal-aloft-manhattan-downtown-financial-district",
    "nycrl-residence-inn-new-york-downtown-manhattan-world-trade-center-area",
    "nyclr-residence-inn-new-york-downtown-manhattan-financial-district",
    "nychw-11-howard-new-york-a-member-of-design-hotels",
    "nyctr-sheraton-tribeca-new-york-hotel",
    "nycom-moxy-nyc-lower-east-side",
    "nycmt-courtyard-new-york-manhattan-soho",
    "nycot-moxy-nyc-east-village",
    "nycbk-new-york-marriott-at-the-brooklyn-bridge",
    "ewrwj-the-westin-jersey-city-newport",
    "ewrnw-courtyard-jersey-city-newport",
    "nycys-sheraton-brooklyn-new-york-hotel",
    "nycyl-aloft-new-york-brooklyn",
    "ewrjr-residence-inn-jersey-city",
    "nycnu-w-new-york-union-square",
    "ewrhb-w-hoboken",
    "nyceb-the-new-york-edition",
    "nycmr-the-moore-a-member-of-design-hotels",
    "nycxb-moxy-brooklyn-williamsburg",
    "nycos-moxy-nyc-chelsea",
    "nycec-aloft-new-york-chelsea",
    "nycro-the-ritz-carlton-new-york-nomad",
    "nyctl-towneplace-suites-new-york-manhattan-chelsea",
    "nycbf-fairfield-inn-and-suites-new-york-brooklyn",
    "nycly-towneplace-suites-new-york-brooklyn",
    "nyctm-fairfield-inn-and-suites-new-york-manhattan-fifth-avenue",
    "nycox-moxy-nyc-times-square",
    "nycmw-fairfield-inn-and-suites-new-york-manhattan-times-square-south",
    "nycsh-springhill-suites-new-york-manhattan-times-square-south",
    "nycjj-courtyard-new-york-manhattan-midtown-west",
    "nycmf-four-points-manhattan-midtown-west",
    "nycet-courtyard-new-york-manhattan-times-square-west",
    "nycri-residence-inn-new-york-manhattan-times-square",
    "nycmd-courtyard-new-york-manhattan-times-square",
    "nycel-element-new-york-times-square-west",
    "nyczw-the-westin-new-york-grand-central",
    "nycfi-fairfield-new-york-manhattan-times-square",
    "nyctf-four-points-midtown-times-square",
    "nycde-delta-hotels-new-york-times-square",
    "nycsw-the-westin-new-york-at-times-square",
    "nycak-the-algonquin-hotel-times-square-autograph-collection",
    "nycts-towneplace-suites-new-york-manhattan-times-square",
    "ewrsl-sheraton-lincoln-harbor-hotel",
    "nycwh-w-new-york-times-square",
    "nyclx-the-lexington-hotel-autograph-collection",
    "nycha-residence-inn-new-york-manhattan-midtown-east",
    "nycte-the-times-square-edition",
    "nycrt-renaissance-new-york-times-square-hotel",
    "nycst-sheraton-new-york-times-square-hotel",
    "nycmx-the-luxury-collection-hotel-manhattan-midtown",
    "nycpk-courtyard-new-york-manhattan-central-park",
    "nycpr-residence-inn-new-york-manhattan-central-park",
    "nycmo-le-meridien-new-york-central-park",
    "nyccp-the-ritz-carlton-new-york-central-park",
    "nycex-jw-marriott-essex-house-new-york",
    "ispva-aloft-long-island-city-manhattan-view",
    "lgaaw-envue-autograph-collection",
    "nycql-courtyard-long-island-city-new-york-manhattan-view",
    "lgark-residence-inn-weehawken-port-imperial",
    "nycqt-towneplace-suites-long-island-city-manhattan-view",
    "ewrcu-residence-inn-secaucus-meadowlands",
    "ewras-aloft-secaucus-meadowlands",
    "lgaew-courtyard-edgewater-nyc-area",
    "nyclh-aloft-harlem",
    "ewrel-element-harrison-newark",
    "lgaal-aloft-new-york-laguardia-airport",
    "ewrca-courtyard-newark-liberty-international-airport",
    "ewrmd-residence-inn-east-rutherford-meadowlands",
    "ewreb-residence-inn-newark-elizabeth-liberty-international-airport",
    "lgasi-sheraton-laguardia-east-hotel",
    "nycfl-four-points-flushing",
    "nycwu-the-westin-flushing-laguardia-airport",
    "ewrnr-renaissance-newark-airport-hotel",
    "ewrew-element-new-york-wood-ridge",
    "nycrj-residence-inn-new-york-jfk-airport",
    "nycjf-courtyard-new-york-jfk-airport",
    "nycbx-residence-inn-new-york-the-bronx-at-metro-center-atrium",
    "ewrak-the-mc-hotel-autograph-collection",
    "ewrog-residence-inn-west-orange",
    "ewrcp-courtyard-paramus",
    "hpnri-residence-inn-new-rochelle",
    "ewrbg-residence-inn-woodbridge-edison-raritan-center",
    "hpnyk-residence-inn-yonkers-westchester-county",
    "ewrdb-delta-hotels-woodbridge",
    "ispgc-residence-inn-long-island-garden-city",
    "ewrwy-residence-inn-wayne",
    "ewred-courtyard-edison-woodbridge",
    "ewrrs-sheraton-edison",
    "hpnob-residence-inn-orangeburg-rockland-bergen",
    "ewrsr-residence-inn-saddle-river",
    "ewrsp-sheraton-parsippany-hotel",
    "ewrmv-courtyard-montvale",
    "ewrwm-the-westin-governor-morris-morristown",
    "nycap-the-opus-westchester-autograph-collection",
    "nycwp-residence-inn-white-plains-westchester-county",
    "ewrps-courtyard-parsippany",
    "hpnsi-sheraton-tarrytown-hotel",
    "hpnry-courtyard-rye",
    "ewrrb-courtyard-lincroft-red-bank",
    "ewrww-residence-inn-new-brunswick-tower-center-blvd"
]

records = []
total_records = 1000

for _ in range(total_records):
    hotel_id = random.choice(hotel_ids)
    check_in = datetime.now() + timedelta(days=random.randint(1,30))
    check_out = check_in + timedelta(days=random.randint(1,5))
    guest_count = 1
    records.append([hotel_id, check_in.strftime('%Y-%m-%d'), check_out.strftime('%Y-%m-%d'), guest_count])

# Write to CSV
with open('../hotels_booking_1000.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['hotel_id', 'check_in_date', 'check_out_date', 'guest_count'])
    writer.writerows(records)
